Content:
    Salamander:
        root_dir: ${ROOT_DIR}/doc/content
    framework:
        root_dir: ${MOOSE_DIR}/framework/doc/content
    chemical_reactions:
        root_dir: ${MOOSE_DIR}/modules/chemical_reactions/doc/content
    electromagnetics:
        root_dir: ${MOOSE_DIR}/modules/electromagnetics/doc/content
    fluid_properties:
        root_dir: ${MOOSE_DIR}/modules/fluid_properties/doc/content
    heat_transfer:
        root_dir: ${MOOSE_DIR}/modules/heat_transfer/doc/content
    misc:
        root_dir: ${MOOSE_DIR}/modules/misc/doc/content
    navier_stokes:
        root_dir: ${MOOSE_DIR}/modules/navier_stokes/doc/content
    phase_field:
        root_dir: ${MOOSE_DIR}/modules/phase_field/doc/content
    reactor:
        root_dir: ${MOOSE_DIR}/modules/reactor/doc/content
    rdg:
        root_dir: ${MOOSE_DIR}/modules/rdg/doc/content
    ray_tracing:
        root_dir: ${MOOSE_DIR}/modules/ray_tracing/doc/content
    scalar_transport:
        root_dir: ${MOOSE_DIR}/modules/scalar_transport/doc/content
    solid_mechanics:
        root_dir: ${MOOSE_DIR}/modules/solid_mechanics/doc/content
    solid_properties:
        root_dir: ${MOOSE_DIR}/modules/solid_properties/doc/content
    stochastic_tools:
        root_dir: ${MOOSE_DIR}/modules/stochastic_tools/doc/content
    subchannel:
        root_dir: ${MOOSE_DIR}/modules/subchannel/doc/content
    thermal_hydraulics:
        root_dir: ${MOOSE_DIR}/modules/thermal_hydraulics/doc/content
    modules:
        root_dir: ${MOOSE_DIR}/modules/doc/content
        content:
            - citing.md
            - help/development/VSCode.md
            - help/development/analyze_jacobian.md
            - help/finite_element_concepts/nodal_patch_recovery.md
            - application_development/performance_benchmarking.md
            - application_usage/restart_recover.md
            - application_usage/command_line_usage.md
    python:
        root_dir: ${MOOSE_DIR}/python/doc/content
        content:
            - python/mms.md
            - python/MooseDocs/**
            - python/moosesqa/index.md
            - python/source/moosetree/Node.md
            - python/testers/**
            - python/CSVDiff.md
            - python/TestHarness.md
    tmap8:
        root_dir: ${ROOT_DIR}/tmap8/doc/content
    cardinal:
        root_dir: ${ROOT_DIR}/cardinal/doc/content
        content: !include ${ROOT_DIR}/doc/cardinal_nek_exclude.yml

Renderer:
    type: MooseDocs.base.MaterializeRenderer
Extensions:
    MooseDocs.extensions.navigation:
        name: SALAMANDER
        repo: https://github.com/idaholab/salamander
        menu:
            Getting Started:
                Installation: getting_started/installation.md
                SALAMANDER on HPC: getting_started/hpc.md
                Using SALAMANDER: getting_started/using_salamander.md
                User Notes: getting_started/salamander_user_notes.md
                Contributing to SALAMANDER: getting_started/contributing.md
            Documentation:
                SALAMANDER-only Syntax: syntax/salamander_only.md
                Complete Code Syntax: syntax/index.md
                V&V and Examples: /verification_validation_examples/index.md
                Publications using SALAMANDER: publications.md
            Software Quality:
                Software Quality Assurance (SQA) Information: /sqa/index.md
                Code Standards: sqa/salamander_scs.md
                Code Coverage: https://mooseframework.inl.gov/salamander/docs/coverage
            Help:
              SALAMANDER Issues Page: https://github.com/idaholab/SALAMANDER/issues
              SALAMANDER Discussion Forum: https://github.com/idaholab/salamander/discussions
              MOOSE FAQ page: https://mooseframework.inl.gov/help/faq/index.html
              MOOSE Discussion Forum: https://github.com/idaholab/moose/discussions
    MooseDocs.extensions.appsyntax: disable
#        executable: ${ROOT_DIR}
#        remove:
#            framework: !include ${MOOSE_DIR}/framework/doc/remove.yml
#            cardinal:
#                - /ICs/BulkEnergyConservationIC
#                - /Cardinal/ICs/BulkEnergyConservation/BulkEnergyConservationICAction
#                - /Cardinal/ICs/VolumetricHeatSource/VolumetricHeatSourceICAction
    MooseDocs.extensions.common:
        shortcuts: !include ${MOOSE_DIR}/framework/doc/globals.yml
    MooseDocs.extensions.acronym: disable
#        acronyms:
#            framework: !include ${MOOSE_DIR}/framework/doc/acronyms.yml
#            cardinal: !include ${ROOT_DIR}/cardinal/doc/acronyms.yml
#            salamander:
#                SALAMANDER: Software for Advanced Large-scale Analysis of MAgnetic confinement for Numerical Design, Engineering & Research
#                PIC: particle-in-cell
#                CFD: computational fluid dynamics
#                CAD: computer-aided design
    MooseDocs.extensions.sqa:
        active: true
        categories: # commented-out categories are not available
            salamander: !include ${ROOT_DIR}/doc/sqa_salamander.yml
            framework: !include ${MOOSE_DIR}/framework/doc/sqa_framework.yml
            #chemical_reactions: !include ${MOOSE_DIR}/modules/chemical_reactions/doc/sqa_chemical_reactions.yml
            electromagnetics: !include ${MOOSE_DIR}/modules/electromagnetics/doc/sqa_electromagnetics.yml
            fluid_properties: !include ${MOOSE_DIR}/modules/fluid_properties/doc/sqa_fluid_properties.yml
            heat_transfer: !include ${MOOSE_DIR}/modules/heat_transfer/doc/sqa_heat_transfer.yml
            misc: !include ${MOOSE_DIR}/modules/misc/doc/sqa_misc.yml
            navier_stokes: !include ${MOOSE_DIR}/modules/navier_stokes/doc/sqa_navier_stokes.yml
            phase_field: !include ${MOOSE_DIR}/modules/phase_field/doc/sqa_phase_field.yml
            reactor: !include ${MOOSE_DIR}/modules/reactor/doc/sqa_reactor.yml
            rdg: !include ${MOOSE_DIR}/modules/rdg/doc/sqa_rdg.yml
            ray_tracing: !include ${MOOSE_DIR}/modules/ray_tracing/doc/sqa_ray_tracing.yml
            scalar_transport: !include ${MOOSE_DIR}/modules/scalar_transport/doc/sqa_scalar_transport.yml
            solid_mechanics: !include ${MOOSE_DIR}/modules/solid_mechanics/doc/sqa_solid_mechanics.yml
            solid_properties: !include ${MOOSE_DIR}/modules/solid_properties/doc/sqa_solid_properties.yml
            stochastic_tools: !include ${MOOSE_DIR}/modules/stochastic_tools/doc/sqa_stochastic_tools.yml
            subchannel: !include ${MOOSE_DIR}/modules/subchannel/doc/sqa_subchannel.yml
            thermal_hydraulics: !include ${MOOSE_DIR}/modules/thermal_hydraulics/doc/sqa_thermal_hydraulics.yml
            tmap8: !include ${ROOT_DIR}/tmap8/doc/sqa_tmap8.yml
            #cardinal: !include ${ROOT_DIR}/cardinal/doc/sqa_cardinal.yml
        reports: !include ${ROOT_DIR}/doc/sqa_reports.yml
        repos:
            default: https://github.com/idaholab/salamander
    MooseDocs.extensions.template:
        active: true
    MooseDocs.extensions.bibtex:
        duplicates:
            - hales15homogenization
            - kim_phase-field_1999
            - Incropera2002
            - petersen
            - Simon2024PBNC # referenced here and in TMAP8
            - todreas2021nuclear # referenced in both THM and Subchannel
            - rhebergen2017analysis # referenced in both Navier Stokes and Framework
